# Generated by Django 2.2.24 on 2021-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0002_auto_20211110_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.DateField(default=django.utils.timezone.now)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_percentage', to='backendapis.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.DateField(default=django.utils.timezone.now)),
                ('purchased_products', models.IntegerField()),
                ('offred_products', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_offer', to='backendapis.Product')),
            ],
        ),
    ]
