# Generated by Django 2.2.24 on 2021-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0003_discountoffer_discountpercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffer',
            name='offred_products',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discountoffer',
            name='purchased_products',
            field=models.IntegerField(default=2),
        ),
    ]
