# Generated by Django 2.2.24 on 2021-11-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0005_auto_20211110_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpercentage',
            name='reduction_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
