# Generated by Django 2.2.24 on 2021-11-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0006_auto_20211110_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_offer', to='backendapis.Product', unique=True),
        ),
        migrations.AlterField(
            model_name='discountpercentage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_percentage', to='backendapis.Product', unique=True),
        ),
    ]
