# Generated by Django 2.2.24 on 2021-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0010_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/product.png', null=True, upload_to='uploads/'),
        ),
    ]
