# Generated by Django 2.2.24 on 2021-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapis', '0011_auto_20211113_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/product.png', null=True, upload_to='uploads/'),
        ),
    ]
